name = "esimfans"
compatibility_date = "2024-04-01"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Workers Assets SPA configuration
[assets]
directory = "./dist"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"

# Cloudflare D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "wappa-db"
database_id = "a2d31d7e-e3b4-4e47-95e2-ebd3c7f18395"

# ...
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[observability.traces]
enabled = true
head_sampling_rate = 1
persist = true

[observability.issue_detection]
enabled = true
# ...

